
language: go

go:
- 1.x
- 1.6
- 1.7.x
- master

install:
# Travis CI builds require "appengine" to function correctly
#- go get google.golang.org/appengine

#deploy:
#  provider: gae
#  keyfile: client-secret.json.enc
#  project: pmd-boomcase
#before_install:
#- openssl aes-256-cbc -K $encrypted_202eef1b0921_key -iv $encrypted_202eef1b0921_iv
#  -in client-secret.json.enc -out client-secret.json -d
